#!/usr/bin/env bash

__retry_pr() {
  local pr="$1"
  local jq_failed_jobs='.[] | select(.conclusion=="FAILURE") | .detailsUrl | capture("/runs/(?<runId>[0-9]+)/job/(?<jobId>[0-9]+)")'
  local job_id_jsonlines=()

  mapfile -t job_id_jsonlines < <(
    gh pr view "$pr" --json "statusCheckRollup" --jq '.statusCheckRollup' \
      | jq -c "$jq_failed_jobs"
  )

  if [[ "${#job_id_jsonlines[@]}" -eq 0 ]]; then
    echo "ℹ️  no failed jobs found for PR $pr" >&2
    return
  fi

  for jsonline in "${job_id_jsonlines[@]}"; do
    local runId jobId
    runId=$(echo "$jsonline" | jq -r ".runId")
    jobId=$(echo "$jsonline" | jq -r ".jobId")
    echo "🔎  ... Retry job $jobId in run $runId (PR $pr)" >&2
    gh run rerun --job "$jobId"
  done
}

cmd_retry() {
  local prs=()
  mapfile -t prs < <(prs::resolve_prs "$@")
  for pr in "${prs[@]}"; do
    echo "🔎  Retry failed jobs for $pr" >&2
    __retry_pr "$pr"
  done
}
